org: nirex2002
app: nirex

service: RecOne-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  architecture: x86_64

  stage: production
  region: ap-south-1

  memorySize: 512
  timeout: 30

  environment:
    NODE_ENV: production

    MONGO_URI: ${env:MONGO_URI}
    MONGO_DB_NAME: ${env:MONGO_DB_NAME}


    JWT_SECRET: ${env:JWT_SECRET}
    JWT_TEMP_SECRET: ${env:JWT_TEMP_SECRET}

    RATELIMIT_WINDOW_MS: ${env:RATELIMIT_WINDOW_MS}
    RATELIMIT_MAX_REQUESTS: ${env:RATELIMIT_MAX_REQUESTS}

    CORS_ORIGIN: ${env:CORS_ORIGIN}

    IMAGEKIT_PUBLIC_KEY: ${env:IMAGEKIT_PUBLIC_KEY}
    IMAGEKIT_PRIVATE_KEY: ${env:IMAGEKIT_PRIVATE_KEY}
    IMAGEKIT_URL_END_POINT: ${env:IMAGEKIT_URL_END_POINT}

functions:
  api:
    handler: src/handler.handler
    timeout: 28

    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!src/**"
    - "!*.ts"
    - "!*.md"
    - "dist/**"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false

    target: node22
    platform: node

    keepNames: true

    # Important for native packages such as sharp
    external:
      - sharp

    exclude:
      - aws-sdk

    packager: npm
    installExtraArgs:
      - "--include=optional"